# Generated by Django 2.1.7 on 2019-03-16 08:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='needs',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
