# Generated by Django 2.1.7 on 2019-04-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_needs1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs1',
            name='nname',
        ),
        migrations.DeleteModel(
            name='needs1',
        ),
    ]
