# Generated by Django 2.1.7 on 2019-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donarsite', '0003_auto_20190324_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdonations',
            name='dname',
        ),
        migrations.AddField(
            model_name='accepteddonations',
            name='status',
            field=models.CharField(default='R', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='pendingdonations',
        ),
    ]
